title: Devon Youth Wind Orchestra
baseurl: "/dywo-website"
url: "https://owen-kellie-smith.github.io"
theme: minima

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:name/
